---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: NFS2.EXAMPLE.COM
    path: "/path/on/nfs/server"