---
### Values replaced by settings/name.properties as indicated
# metadata.name: app-name = app_name
# Under spec.template.spec.containers.0
# .name: app-container = container_name
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
        - name: app-container
          envFrom:
          - configMapRef:
              name: app-env
            