---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
spec:
  template:
    spec:
      ## https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
      ## nodeName will pin the pod to run only on the k8s node where your USB
      ## Zigbee controller is inserted.
      ## This is only needed if you are using a USB dongle! For network-based
      ## controllers, like the UZG-01, this setting is unnecessary.
      # nodeName: my-k8-node-name
      containers:
        - name: zigbee2mqtt
          volumeMounts:
            - name: z2m-data
              mountPath: /app/data
            ## Uncomment these if you need them
            # - name: z2m-udev
            #   mountPath: /run/udev
            # - name: zigbee-device
            #   mountPath: /dev/ttyACM0
      ## Uncomment these if you need them
      # volumes:
      #   - name: z2m-udev
      #     hostPath:
      #       path: /run/udev
      #   - name: zigbee-device
      #     hostPath:
      #       path: /dev/ttyACM0
  ## Uncomment this if you need to change anything, like specifying a non-default
  ## storageClassName, or using more or less storage.
  # volumeClaimTemplates:
  #   - metadata:
  #       name: z2m-data
  #     spec:
  #       storageClassName: MY_STORAGECLASS
  #       accessModes: [ "ReadWriteOnce" ]
  #       resources:
  #         requests:
  #           storage: 100Mi
