---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-pvc
spec:
  storageClassName: ""
  volumeName: external-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
