---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-app
spec:
  template:
    spec:
      containers:
      - name: pms-app
        volumeMounts:
        - mountPath: /plex
          name: pms-media
      volumes:
      - name: pms-media
        persistentVolumeClaim:
          claimName: pms-media-pvc
