---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
