---
### Values replaced by settings/name.properties as indicated
# metadata.name: app-name = app_name
### Values replaced by settings/server.properties as indicated
# Under spec.volumeClaimTemplates.0.spec
# .storageClassName: default = storageClass
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-name
spec:
  volumeClaimTemplates:
    - metadata:
        name: app-storage-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi
        storageClassName: default
