---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

commonLabels:
  app: nextcloud
  version: "29"

resources:
  - redis
  - mariadb
  - nextcloud
  - cron
  # - external

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/3/value"
      value: "db.nextcloud.svc.cluster.local"
    - op: replace
      path: "/spec/template/spec/containers/0/env/4/value"
      value: "redis.nextcloud.svc.cluster.local"
  target:
    kind: Deployment
    name: app