---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis
  - mariadb
  - nextcloud
  - cron

secretGenerator:
- name: kustom-secret
  literals:
  envs:
  - .env.secretbase
