---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: plex

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: plex-0
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/part-of: plex

images:
  - name: untergeek/pms-docker
    newTag: 1.41.6.9685

configMapGenerator:
  - name: settings
    envs:
      - settings/server.properties

components:
  - ../../components/storage/config/volumeClaim
  - ../../components/storage/media/nfs
# Uncomment o use TLS using values in settings/server.properties
  - ../../components/ingress/tls
# Uncomment to enable nvidia GPU support
  - ../../components/nvidia

patches:
# Need to have the container base replaced here for images to work above
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/image"
      value: "untergeek/pms-docker:latest"
  target:
    kind: StatefulSet
    name: plex-app
- patch:
  path: patches/service.yaml

replacements:
- path: replacements/server.yaml
