---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
