---
### Values replaced by settings/name.properties as indicated
# Under metadata.name can be set by `ingress_name`
### Values replaced by settings/server.properties as indicated
# metadata.annotations.cert-manager.io/cluster-issuer can be set by `ingress_cert_manager`
# spec.tls.0.hosts.0 can be set by `ingress_fqdn`
# spec.tls.0.hosts.secretName can be set by `ingress_tls`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations: 
    cert-manager.io/cluster-issuer: KUSTOMIZE
  labels:
    app.kubernetes.io/component: tls
spec:
  tls:
    - hosts:
      - KUSTOMIZE
      secretName: KUSTOMIZE
