---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pms-media-pv
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
