---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-media-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 3Ti
  volumeName: pms-media-pv
  