---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-media-pvc
spec:
  storageClassName: nfs-csi
  volumeName: pms-media-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Ti
