---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app.kubernetes.io/component: web
spec:
  ingressClassName: nginx
  rules:
  - host: KUSTOMIZE
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080

# Add basic auth and TLS support via components in kustomization.yaml
