---
### Values replaced by settings/name.properties as indicated
# Under metadata:
# .labels.app can be set by `app_label`
# .name can be set by `app_name`
# Under spec:
# .containers.name can be set by `container_name `
# .ports.0.name can be set by `svc_port_name`
### Values replaced by settings/server.properties as indicated
# Under spec.template.spec.containers.0:
# .ports.0.containerPort can be set by `svc_port`
# .ports.0.protocol can be set by `svc_protocol`
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-label
  name: app-name
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-label
  template:
    metadata:
      labels:
        app: app-label
    spec:
      containers:
        - name: app-container
          image: OWNER/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "896Mi"
