---
apiVersion: networking.k8s.io/v1
kind: Ingress
# KUSTOMIZE values replaced by values in settings/config.properties as noted in comments
metadata:
  name: ingress
  labels:
    app.kubernetes.io/component: web
spec:
  ingressClassName: nginx
  rules:
    # ingress_fqdn
  - host: KUSTOMIZE
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
