---
### Values replaced by settings/name.properties as indicated
# metadata.name can be set by `svc_name`
### Values replaced by settings/server.properties as indicated
# spec.type can be set by `svc_type`
# spec.loadBalancerIP can be set by `loadbalancer_ip`
# spec.externalTrafficPolicy can be set by `ext_TrafficPolicy`
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  # annotations:
  #   metallb.universe.tf/loadBalancerIPs: KUSTOMIZE
spec:
  type: LoadBalancer
  loadBalancerIP: <LOADBALANCER_IP>
  externalTrafficPolicy: Local
