---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

components:
  # - components/ingress/tls
  # - components/statefulset/otel

namespace: ntfy

commonLabels:
  app.kubernetes.io/name: ntfy
  app.kubernetes.io/instance: ntfy-0
  app.kubernetes.io/version: 2.11.0
  app.kubernetes.io/part-of: ntfy
  app.kubernetes.io/managed-by: Kustomize

images:
  - name: binwiederhier/ntfy
    newTag: v2.11.0

configMapGenerator:
  # Settings used with replacements
  - name: settings
    envs:
      - settings/config.properties
  # Parse server.yml file contents into ConfigMap
  - name: server-config
    files: 
      - patches/configmap/server.yml

# Only uncomment if you need to patch it
# patches:
# ## StatefulSet settings:
# - patch:
#   path: patches/statefulset.yaml

replacements:
  - path: replacements/statefulset.yaml
  - path: replacements/ingress.yaml
