---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

namespace: ntfy

images:
  - name: binwiederhier/ntfy
    newTag: v2.11.0

# Parse server.yml file contents into ConfigMap
configMapGenerator:
  - name: server-config
    files: 
      - patches/configmap/server.yml

patches:
## StatefulSet settings:
- patch:
  path: patches/statefulset/settings.yaml
# Ingress settings:
- patch: |-
    - op: replace
      path: "/spec/rules/0/host"
      value: "<NTFY.EXAMPLE.COM>"  # Replace with your FQDN
  target:
    kind: Ingress
    name: ingress
# Uncomment if you plan to enable TLS encryption on your Ingress
# - patch:
#   path: patches/ingress/settings.yaml
