apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

namespace: pihole

images:
  - name: pihole/pihole
    newTag: 2024.07.0

configMapGenerator:
  - name: custom-dnsmasq
    behavior: replace
    files:
      - patches/configmap/02-mymasq.conf

secretGenerator:
- name: ui-secret
  literals:
  envs:
  - .env.secret

patches:
### StatefulSet settings:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name"
      value: "ui-secret"  # The name from the secretGenerator above
  target:
    kind: StatefulSet
    name: pihole
##
## Edit patches/statefulset/settings.yaml for ALL OTHER SETTINGS
- patch:
  path: patches/statefulset/settings.yaml
### Service settings:
- patch:
  path: patches/service/tcp/settings.yaml
- patch:
  path: patches/service/udp/settings.yaml
## Ingress settings:
- patch: |-
    - op: replace
      path: "/spec/rules/0/host"
      value: "<PIHOLE-UI.EXAMPLE.COM>"  # Replace with your FQDN
  target:
    kind: Ingress
    name: ingress
# Uncomment if you plan to enable TLS encryption on your Ingress
# - patch:
#   path: patches/ingress/settings.yaml
