---
kind: Service
apiVersion: v1
metadata:
  name: tcp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: key-to-share-<LOADBALANCER_IP>
spec:
  loadBalancerIP: <LOADBALANCER_IP>

# If you are not using metallb, remove the annotation.
