---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  storageClassName: ""
  volumeName: app-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
