---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

commonLabels:
  app: nextcloud
  version: "29"

resources:
  - base
  # - base/external # Only if you also want to mount external storage

images:
  - name: nextcloud
    newTag: 29.0.7-apache
  - name: redis
    newTag: 7.4.0-alpine3.20
  - name: mariadb
    newTag: "11.5.2"

secretGenerator:
- name: kustom-secret
  behavior: replace
  literals:
  envs:
  - .env.secret

patches:
# MariaDB patches
## Storage
- patch: |-
    - op: replace
      path: "/spec/resources/requests/storage"
      value: "10Gi"
  target:
    kind: PersistentVolumeClaim
    name: db-pvc
# NEXTCLOUD
## STORAGE
### PVs (need to add NFS storage volume before the PVC)
- patch:
  path: patches/nextcloud/pv/settings.yaml
# Only uncomment if resources base/external is also uncommented above
# - patch:
#   path: patches/external/pv/settings.yaml
### PVCs
- patch:
  path: patches/nextcloud/pvc/settings.yaml
# Only uncomment if resources base/external is also uncommented above
# - patch:
#   path: patches/external/pvc/settings.yaml
## INGRESS
- patch:
  path: patches/nextcloud/ingress/settings.yaml
## DEPLOYMENT
- patch:
  path: patches/nextcloud/deployment/settings.yaml
