---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

commonLabels:
  app: nextcloud

resources:
  - base
  # - base/external # Only if you also want to mount external storage

images:
  - name: nextcloud
    newTag: 30.0.0-apache
  - name: redis
    newTag: 7.4.0-alpine3.20
  - name: mariadb
    newTag: lts-noble  # For lts-noble, imagePullPolicy has been set to Always

secretGenerator:
- name: kustom-secret
  behavior: replace  # This must be 'replace' as we have it also set in `base`
  literals:
  envs:
  - .env.secret

patches:
# MariaDB patches
- patch: |-
    ## Storage
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 10Gi
    ## Uncomment and add a value if you need to define a storageClassName
    # - op: add
    #   path: /spec/volumeClaimTemplates/0/spec/storageClassName
    #   value: ""
    ## StatefulSet
    ## Uncomment this to make it pull the latest lts-noble image Always
    # - op: replace
    #   path: /spec/template/spec/containers/0/imagePullPolicy
    #   value: Always
  target:
    kind: StatefulSet
    name: db
# NEXTCLOUD
## App storage
- patch:
  path: patches/nextcloud/pv/settings.yaml
- patch:
  path: patches/nextcloud/pvc/settings.yaml
## External storage
## Only uncomment if base/external is also uncommented in the resources block.
# - patch:
#   path: patches/external/pv/settings.yaml
# - patch:
#   path: patches/external/pvc/settings.yaml
## INGRESS
- patch:
  path: patches/nextcloud/ingress/settings.yaml
## DEPLOYMENT
- patch:
  path: patches/nextcloud/deployment/settings.yaml
