---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-config-pvc
spec:
  storageClassName: nfs-csi
  volumeName: pms-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
