---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-media-pvc
spec:
  storageClassName: ""
  volumeName: pms-media-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
