---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
      - "Z2M.EXAMPLE.COM"
      secretName: MY_TLS_SECRET

# replace Z2M.EXAMPLE.COM with your FQDN for the frontend
# replace MY_TLS_SECRET with the name of your TLS secret (must be in same namespace)
