---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations: 
    cert-manager.io/cluster-issuer: KUSTOMIZE
spec:
  tls:
    - hosts:
      - KUSTOMIZE
      secretName: KUSTOMIZE
