---
### Values replaced by settings/name.properties as indicated
# Under metadata:
# .labels.app: app-label = label_app
# .name: app-name = app_name
# Under spec:
# .containers.name: app-container = container_name 
# .serviceName: sts-name = sts_name
### Values replaced by settings/server.properties as indicated
# Under spec.template.spec.containers.0:
# .image: OWNER/IMAGE:TAG = container_image
# .ports.0.name: http = service_port_name
# .ports.0.containerPort: 80 = service_port
# .ports.0.protocol: TCP = service_protocol
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi