---
### Values replaced by settings/name.properties as indicated
# Under metadata.name can be set by pvc_name
### Values replaced by settings/server.properties as indicated
# spec.accessModes[0] can be set by appVol_accessMode
# spec.resources.requests.storage can be set by appVol_storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi