---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntfy
spec:
  template:
    spec:
      containers:
        - name: ntfy 
          env:
            - name: TZ
              value: America/Chicago
            - name: NTFY_DEBUG
              value: "false"
            - name: NTFY_LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: 150m
              memory: 150Mi
            limits:
              cpu:  200m
              memory: 300Mi
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi