---
### Values replaced by settings/name.properties as indicated
# metadata.name can be set by `app_name`
# Under spec.template.spec.containers.0
# .name can be set by `container_name`
# Under .volumeMounts.0
# .name can be set by `configmap_vol`
# Under spec.template.spec.volumes.0
# .name can be set by `configmap_name`
### Values replaced by settings/server.properties as indicated
# Under spec.template.spec.containers.0.volumeMounts.0
# .mountPath can be set by `cm_mountPath`
# Under spec.template.spec.volumes.0.configMap
# .subPath can be set by `cm_subPath`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - name: app-container
        volumeMounts:
        - name: configmap-vol
          mountPath: /path/to/config
          subPath: app.conf
      volumes:
      - name: configmap-vol
        configMap:
          defaultMode: 420
          name: app-cm
