---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pms-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"