---
### Values replaced by settings/name.properties as indicated
# metadata.name can be set by `ingress_name`
# spec.rules.0.http.paths.0.backend.service.name can be set by `svc_name`
### Values replaced by settings/server.properties as indicated
# spec.ingressClassName can be set by `ingressClassName`
# Under spec.rules.0.host can be set by `ingress_fqdn`
# spec.rules.0.http.paths.0.backend.service.port.number: 80 can be set by `svc_port`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: host.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-svc
            port:
              number: 80
