apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto

data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    protocol mqtt
    log_dest stdout

    persistence true
    persistence_file persistence.db
    persistence_location /mosquitto/data

    password_file /mosquitto/config/password.txt
    acl_file /mosquitto/config/acl.txt
