---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"
