---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
      - "<REVERSE.EXAMPLE.COM>"
      secretName: <MY_TLS_SECRET>

# Replace <REVERSE.EXAMPLE.COM> with your FQDN
# Replace <MY_TLS_SECRET> with your premade TLS secret (must be in same namespace)
