---
kind: Service
apiVersion: v1
metadata:
  name: udp-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports: 
    - protocol: UDP
      port: 53
      name: dnsudp
      targetPort: 53