---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
  volumeName: external-pv
