---
### Values replaced by settings/name.properties as indicated
# Under metadata:
# .name can be set by `svc_name`
# Under spec:
# .selector.app can be set by `app_label`
# .name can be set by `svc_port_name`
### Values replaced by settings/server.properties as indicated
# Under spec.ports.0:
# .protocol can be set by `svc_protocol`
# .port can be set by `svc_port`
# .targetPort can be set by `svc_targetPort`
kind: Service
apiVersion: v1
metadata:
  name: app-svc
spec:
  type: ClusterIP
  selector:
    app: app-label
  ports:
    - protocol: TCP
      port: 80
      name: app-port
      targetPort: 80
