---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

## Uncomment these as needed to enable
# components:
#   - components/ingress/basic_auth
#     # basic_auth for your ingress, since zigbee2mqtt is otherwise unprotected
#   - components/ingress/tls
#     # tls support for your ingress, so web traffic is encrypted. Requires cert-manager
#   - components/statefulset/apm
#     # Elastic APM monitoring of Zigbee2MQTT. Requires a container image that has
#     # this support added and configured.

namespace: zigbee2mqtt

commonLabels:
  app: zigbee2mqtt

images:
  - name: koenkk/zigbee2mqtt
    newTag: 1.41.0
  - name: busybox
    newTag: "1.36"

configMapGenerator:
- name: settings
  envs:
    - settings/apm.properties
    - settings/z2m.properties

secretGenerator:
- name: my-secrets
  literals:
  envs:
    - settings/.env.secrets

### Patches
patches:
## ConfigMap settings:
- patch:
  path: patches/configmap/configuration.yaml
## StatefulSet settings:
- patch:
  path: patches/statefulset/settings.yaml

## These files apply the values from the settings/* files
replacements:
  - path: replacements/statefulset.yaml
  - path: replacements/ingress.yaml
