---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

namespace: zigbee2mqtt

commonLabels:
  app: zigbee2mqtt

images:
  - name: koenkk/zigbee2mqtt
    newTag: 1.40.1
  - name: busybox
    newTag: "1.36"

secretGenerator:
- name: my-secrets
  literals:
  envs:
  - .env.secret

### Patches
patches:
## ConfigMap settings:
- patch:
  path: patches/configmap/configuration.yaml
## StatefulSet settings:
# Use the network_key from secret in our initContainer to create secret.yaml
# Use `my-secrets` from just above here.
# This is where your provided value will be used instead of the 0 - 15 sequence.
- patch: |-
    - op: replace
      path: /spec/template/spec/initContainers/1/env/0
      value:
        name: NETWORK_KEY
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: network_key
  target:
    kind: StatefulSet
    name: zigbee2mqtt
# Configure the remaining items from the patch file
- patch:
  path: patches/statefulset/settings.yaml
## Ingress settings:
- patch: |-
    - op: replace
      path: "/spec/rules/0/host"
      value: "Z2M.EXAMPLE.COM"
  target:
    kind: Ingress
    name: ingress
- patch:
  path: patches/ingress/settings.yaml
