---
### Values replaced by settings/name.properties as indicated
# metadata.name can be set by `app_name`
# spec.template.spec.containers.0.name can be set by `container_name`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
        - name: app-container
          envFrom:
          - configMapRef:
              name: app-env
            