---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: plex-0
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/part-of: plex

components:
  - components/storage/config/volumeClaim
  # If using something other than NFS, you may need to figure it out yourself
  - components/storage/media/nfs
# Uncomment o use TLS using values in settings/server.properties
  # - components/ingress/tls
# Uncomment to enable nvidia GPU support
  # - components/nvidia

configMapGenerator:
- envs:
  - settings/server.properties
  name: settings

images:
- name: index.docker.io/plexinc/pms-docker
  newTag: latest

patches:
# If you plan on using a different image to enable Nvidia GPU support, you must
# do so here as well as include your image in the images section above.
# Replace the value of the image with the one you want to use.
# - patch: |-
#     - op: replace
#       path: "/spec/template/spec/containers/0/image"
#       value: "index.docker.io/plexinc/pms-docker:latest"
#   target:
#     kind: StatefulSet
#     name: plex-app

replacements:
- path: replacements/server.yaml
