---
### Values replaced by settings/name.properties as indicated
# metadata.name -name can be set by `app_name`
# Under spec.template.spec.containers.0
# .name can be set by `container_name`
# Under .volumeMounts.0
# .name can be set by `app-storage_vol`
# Under spec.volumeClaimTemplates.0
# .metadata.name can be set by `app-storage_vol`
### Values replaced by settings/server.properties as indicated
# Under spec.template.spec.containers.0.volumeMounts.0
# .mountPath can be set by `appVol_mountPath`
# Under spec.volumeClaimTemplates.0.spec.resources.requests
# .storage can be set by `appVol_storage`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
        - name: app-container
          volumeMounts:
            - name: app-storage-vol
              mountPath: /path/to/storage
      volumes:
        - name: app-storage-vol
          persistentVolumeClaim:
            claimName: app-pvc
